### ISSUE TITLE
マニュアルについて

### ISSUE THREAD

**Issue by Nobu19800** [tbou30897/OpenRTM_SNS_filter_system#2]
細かいことですが、マニュアルの誤字が気になりました。

- 11ページのTimedShoatSeqは、TimedShortSeqです
-  7ページのRELESEはRELEASEです

**Comment by tbou30897** [comment]
ご指摘ありがとうございます。
先程修正致しましたので、ご確認をお願い致します。

**Comment by Nobu19800** [comment]
RELEASEではなくRELASEになっています。

**Comment by tbou30897** [comment]
度々のご指定ありがとうございます。
修正いたしましたので、issueを閉じさせていただきます。
