### ISSUE TITLE
sentiment_analysisコンポーネントについて

### ISSUE THREAD

**Issue by Nobu19800** [tbou30897/OpenRTM_SNS_filter_system#3]
sentiment_analysisコンポーネントのOutPortからは、配列の最初にscoreという文字列が入って、その後に数値が入った['score', '0.9701453447341919', '0.9454545378684998', ・・・]のようなデータが送信されるようですが、TimedWStringSeq型のデータに数値を文字列に変換して格納するのは、数値から文字列の変換、文字列から数値の変換が発生して無駄も多いですし、やり取りするデータのサイズも文字列の方が大きくなるので、改善したほうがいいと思います。
他のRTCについても、morphological_analysisで単語のリスト、品詞のリストを異なるOutPortから送信して、restricted_wordの2つのInPortでどちらも受信出来たら処理していますが、これについても独自データ型を定義して同時にデータを送信することも検討をお願いします。

**Comment by tbou30897** [comment]
ご指摘ありがとうございます。
独自データ型についてはまだ改善できておりませんが、
senitment_alalysis、result_outのデータポートを増やして（TimedWStringSeqのみから、TimedFloatSeqとTimedWStiringの２つに変更）stiring→floatの変換時の無駄を改善致しました。
