### ISSUE TITLE
RTCの仕様について

### ISSUE THREAD

**Issue by Nobu19800** [tbou30897/OpenRTM_SNS_filter_system#4]
ソースコードを見たところ、RTCの概要がデフォルトのModuleDescriptionになっていたり、vendorがデフォルトのVenderNameになっています。
RTC BuilderでRTCを作成する際に、例えば「基本」の項目では概要やベンダ名等が入力できるようになっています。また、データポートの概要説明なども入力できるようになっており、一部の項目は起動したRTCから情報を取得できるほか、またGitHub用にREADME.mdも生成するようになっているので、そこからRTCの情報を確認できるようになっています。
できれば、RTC BuilderでRTCの情報を入力していただけると、使う側は分かりやすくなると思います。

**Comment by tbou30897** [comment]
ご指摘ありがとうございます。
RTCの概要、vender、カテゴリ等修正致しました。

**Comment by Nobu19800** [comment]
対応していただいてありがとうございます。このissueは閉じます。
