### ISSUE TITLE
SentimentAnalysis関数の実装について

### ISSUE THREAD

**Issue by n-ando** [tbou30897/OpenRTM_SNS_filter_system#5]
sentiment_analysis の以下のコードの部分ですが、解析テキストを引数渡しではなく、メンバ変数渡しとしているのにはなにか意味があるのでしょうか？
self.text をメンバ変数にする必要があるかを考えたほうが良いように思いますし、関数に引数として渡したほうが良いと思います。

また、modelとtokenizerはtext解析のたびにオブジェクトを生成する必要はありますか？逆にこちらをメンバ変数にしたほうが良いようにも思いました。

https://github.com/tbou30897/OpenRTM_SNS_filter_system/blob/0d2363d2aac0e2a5c2f31a989befe463ce831d9c/RTC/SNS%20system%20components/sentiment_analysis/sentiment_analysis.py#L124-L131

**Comment by tbou30897** [comment]
ご指摘ありがとうございます。
SentimentAnalysis関数を削除して、OnActivateにmodel,tokenizer,nlpの定義を、onExecuteに感情分析の出力を移して改良しました。
